openapi: 3.0.1
info:
  title: API Avaliação 2
  description: Atividade1 - Cadastro e consulta de carros com spring
  version: 0.0.1
  termsOfService: https://mockapi.io
servers:
  - url: http://localhost:8080
paths:
  /api/cars:
    get:
      summary: Retorna todos as entidades cadastrados
      
      parameters: 
      - name: nome
        in: query
        schema:
          type: string
        required: false
        
      - name: cor
        in: query
        schema:
          type: string
        required: false
        
      - name: marca
        in: query
        schema:
          type: string
        required: false
        
      - name: page
        in: query
        schema:
          type: integer
        required: false
        
      - name: size
        in: query
        schema:
          type: integer
        required: false
        
      - name: sort
        in: query
        schema:
          type: string
        required: false
        
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                    marca:
                      type: string
                    cor:
                      type: string
                    valor:
                      type: number
                    ano:
                      type: integer
        404:
          description: Não encontrado
          content:
            aplication/json:
              example: "Not Found"
    post:
      summary: Cria nova entidade carro
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chassi: 
                  type: string
                nome: 
                  type: string
                marca: 
                  type: string
                cor: 
                  type: string
                valor: 
                  type: number
                ano: 
                  type: integer
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome: 
                    type: string
                  marca: 
                    type: string
                  cor: 
                    type: string
                  valor: 
                    type: number
                  ano: 
                    type: integer
        400:
          description: "Dados inseridos invalidos"
          
          